### DISCUSSION TITLE
Description of trainer/config_files/*.YAML options

### DISCUSSION THREAD

**Discussion by S0mbre** [JaidedAI/EasyOCR#738] [Q&A]
Would it be possible to make some detailed (or at least brief) description (readme.md) in [trainer/config_files](https://github.com/JaidedAI/EasyOCR/tree/master/trainer/config_files) for the YAML options to train custom models? The provided example is as follows and has but few comments:
```yaml
number: '0123456789'
symbol: "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ €"
lang_char: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'
experiment_name: 'en_filtered'
train_data: 'all_data'
valid_data: 'all_data'
manualSeed: 1111
workers: 6
batch_size: 32 #32
num_iter: 300000
valInterval: 20000
saved_model: '' #'saved_models/en_filtered/iter_300000.pth'
FT: False
optim: False # default is Adadelta
lr: 1.
beta1: 0.9
rho: 0.95
eps: 0.00000001
grad_clip: 5
#Data processing
select_data: 'en_sample' # this is dataset folder in train_data
batch_ratio: '1' 
total_data_usage_ratio: 1.0
batch_max_length: 34 
imgH: 64
imgW: 600
rgb: False
contrast_adjust: False
sensitive: True
PAD: True
contrast_adjust: 0.0
data_filtering_off: False
# Model Architecture
Transformation: 'None'
FeatureExtraction: 'VGG'
SequenceModeling: 'BiLSTM'
Prediction: 'CTC'
num_fiducial: 20
input_channel: 1
output_channel: 256
hidden_size: 256
decode: 'greedy'
new_prediction: False
freeze_FeatureFxtraction: False
freeze_SequenceModeling: False
```
