### ISSUE TITLE
Using custom model with different input size? (rgb: True)

### ISSUE THREAD

**Issue by ckcollab** [JaidedAI/EasyOCR#567]
I've successfully trained my own model, thank you so much for the guidance there, but now when I am trying to use the model I made with `rgb: true` (making it have an input of 3 channels) I get errors for size mismatches:

```
RuntimeError: Given groups=1, weight of size [32, 3, 3, 3], expected 
 input[1, 1, 64, 256] to have 3 channels, but got 1 channels instead
```

This may be due to the downloaded model, or something? I played with `download_enabled` and removing the downloaded model, that gives this error:

```
FileNotFoundError: Missing ./ocr_model/craft_mlt_25k.pth and downloads disabled
```

How do I use the reader **only using** my network? or am I trying to do something that doesn't make any sense? If my training is making great predictions, I'm confused on why I need another model?

```py
reader = easyocr.Reader(
    ['en'], 
    # here's where my custom_model.pth file is
    model_storage_directory="./ocr_model",  
    # here's where my custom_model.py and custom_model.yaml live
    user_network_directory='./ocr_network',   
    recog_network='custom_model'
)
reader.readtext('test.jpg')
```

I believe I set `custom_model.yaml`  up properly:
```yaml
network_params:
  input_channel: 3
  output_channel: 256
  hidden_size: 256
imgH: 64
lang_list:
         - 'en'
character_list: 0123456789!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~ ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
```

## EDIT

Doing the exact same training but with `rgb: False` and everything works, woo! am I missing  out on much without rgb?
